model: FC12
init: kaiming_normal
data_path: "datasets/"
dataset: cifar10

use_full_data: True

batch_size: 128
gpu: 1

criterion: cross_entropy

optim: sgd
lr: 0.01
momentum: 0.9
weight_decay: 0 #0.0001
gamma: 0.5

warm: 0
schedu: False
milestones: [60, 120, 180]
schedumode: multistep

epoch: 200
l1: True
lmbda: 0.00005
regularizer: L1
mode: train
sparse: True
sparse_epoch: 1000

file_path: ' '

save_model: True

lanczos_iter: 128
lanczos_num: 1