model: ResNet18
init: kaiming_normal
data_path: "datasets/"
dataset: cifar100

use_full_data: True

batch_size: 128
gpu: 1

criterion: cross_entropy

optim: sgd
lr: 0.1
momentum: 0.9
weight_decay: 0 #0.000005
gamma: 0.2

warm: 5
schedu: True
milestones: [60, 120, 160]
schedumode: cos

epoch: 200

l1: False
lmbda: 0.00005 #005
regularizer: L1
mode: train

sparse: False
sparse_epoch: 1000

file_path: ' '

save_model: True

lanczos_iter: 128
lanczos_num: 1